version: "3"
services:
  ms-notes:
    container_name: ms-notes
    image: 'ms-notes'
    network_mode: bridge
    restart: always
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "9729:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'test'
      SPRING_CLOUD_CONFIG_URI: '<url>'
      SPRING_CLOUD_CONFIG_USERNAME: '<username>'
      SPRING_CLOUD_CONFIG_PASSWORD: '<password>'