version: "3"
services:
  ms-notes-sandbox:
    container_name: ms-notes-sandbox
    image: 'ms-notes'
    network_mode: bridge
    links:
      - 'ms-notes-db-sandbox:mariadb'
    restart: always
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "9728:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'sandbox'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://ms-notes-db-sandbox:3306/dbnotes'
      SPRING_DATASOURCE_USERNAME: 'sandbox-user'
      SPRING_DATASOURCE_PASSWORD: 'sandbox-password'
    depends_on:
      - ms-notes-db-sandbox

  ms-notes-db-sandbox:
    container_name: ms-notes-db-sandbox
    image: 'mariadb:10.6.4'
    network_mode: bridge
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD : 'yes'
      MARIADB_DATABASE: 'dbnotes'
      MARIADB_USER: 'sandbox-user'
      MARIADB_PASSWORD: 'sandbox-password'
    expose:
      - '3306'